# add your desired knowledge graph components here

person:
  is_a: individual organism
  represented_as: node
  input_label: person

project:
  is_a: event
  represented_as: node
  input_label: project
  properties:
    title: str
    description: str
    labels: str[]
    status: str
    size: str
    priority: str
    iteration: str
    assignees: str[]
    issue: int

iteration:
  is_a: event
  represented_as: node
  input_label: iteration

leads:
  is_a: association
  represented_as: edge
  input_label: leads

part of:
  is_a: association
  represented_as: edge
  input_label: part of
