# add your desired knowledge graph components here

person:
  is_a: individual organism
  represented_as: node
  input_label: person

project:
  is_a: event
  represented_as: node
  input_label: project

iteration:
  is_a: event
  represented_as: node
  input_label: iteration

leads:
  is_a: association
  represented_as: edge
  use_id: false
  input_label: leads
