# add your desired knowledge graph components here

person:
  is_a: individual organism
  represented_as: node
  input_label: person
  properties:
    name: str

project:
  is_a: event
  represented_as: node
  input_label: project
  properties:
    title: str
    description: str
    labels: str[]
    status: str
    size: str
    priority: str
    iteration: str
    assignees: str[]
    issue_number: str

comment:
  is_a: event
  represented_as: node
  input_label: comment
  properties:
    text: str

iteration:
  is_a: event
  represented_as: node
  input_label: iteration

leads:
  is_a: association
  represented_as: edge
  input_label: leads
  source: person
  target: project

part of:
  is_a: association
  represented_as: edge
  input_label: part of
  source: project
  target: iteration

has comment:
  is_a: association
  represented_as: edge
  input_label: has comment
  source: project
  target: comment
  properties:
    recency: int
